### ISSUE TITLE
ImportError: Error loading shared library libz.so.1: No such file or directory

### ISSUE THREAD

**Issue by cairami** [luodeb/Starry#13]
在跑py脚本时，有些需要import binascii的会报错。

/python3.11/ # bin/python3.11 lib/python3.11/test/test__xxsubinterpreters.py
Traceback (most recent call last):
  File "/python3.11//lib/python3.11/test/test__xxsubinterpreters.py", line 14, in <module>
    from test.support import script_helper
  File "/python3.11/lib/python3.11/test/support/script_helper.py", line 11, in <module>
    import zipfile
  File "/python3.11/lib/python3.11/zipfile.py", line 6, in <module>
    import binascii
ImportError: Error loading shared library libz.so.1: No such file or directory (needed by /python3.11/lib/python3.11/lib-dynload/binascii.cpython-311-aarch64-linux-gnu.so)
/python3.11/ # bin/python3.11 lib/python3.11/test/test_misc.py
bin/python3.11: can't open file '/python3.11//lib/python3.11/test/test_misc.py': [Errno 2] No such file or directory
/python3.11/ # bin/python3.11 lib/python3.11/test/test_zlib.py
Traceback (most recent call last):
  File "/python3.11//lib/python3.11/test/test_zlib.py", line 4, in <module>
    import binascii
ImportError: Error loading shared library libz.so.1: No such file or directory (needed by /python3.11/lib/python3.11/lib-dynload/binascii.cpython-311-aarch64-linux-gnu.so)

已经尝试过：
1. export LD_LIBRARY_PATH=/opt/python3.11/lib
2.  检查disk.img的大小（如果大于120M，会被ramfs截断）。但大小为76M
3. 符号链接问题：libz.so.1是libz.so.1.2.13的链接。但我一直用zip打包python3.11目录，disk.img里符号链接已经转为文件。

优先级低。影响所有import binascii的py脚本。

**Comment by cairami** [comment]
根据萧老师建议，在disk.img里建/lib，把python3.11/lib/*.so*拷到/lib，就可以访问到。
